# Generated by Django 3.2.6 on 2021-08-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('discounted_price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('category', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=300)),
            ],
        ),
    ]
