# Generated by Django 3.2.6 on 2021-08-14 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
