# Generated by Django 3.2.6 on 2021-08-14 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_category', '0002_alter_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
